steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/outdecked:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/outdecked:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'outdecked'
      - '--image'
      - 'gcr.io/$PROJECT_ID/outdecked:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'FLASK_ENV=production,DB_HOST=/cloudsql/outdecked:us-central1:outdecked-db,DB_NAME=postgres,DB_USER=postgres,DB_PASSWORD=outdecked-prod-2024'
      - '--add-cloudsql-instances'
      - 'outdecked:us-central1:outdecked-db'

images:
  - 'gcr.io/$PROJECT_ID/outdecked:latest'
